hack/evenement/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "evenements"
urlpatterns = [
    path('', views.liste_evenements, name='liste_evenements'),
    path('evenement/<int:pk>/join/', views.join_event, name='join_event'),
]

hack/hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('login.urls')),
    path('profile/', include('profileUser.urls')),
    path('evenement/', include('evenement.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hack/login/urls.py
from django.urls import path
from . import views


app_name= "login"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

hack/profileUser/urls.py
from django.urls import path
from . import views

app_name= "profiles"
urlpatterns = [
    # Other URL patterns...
    path('', views.profile_view, name='profile'),
    path('certifications/', views.certification_list, name='certification_list'),
    path('create/', views.add_certification, name='add_certifications'),
    path('update/<str:pk>', views.update_certification, name='update_certification'),
    path('delete/<str:pk>', views.delete_certification, name='delete_certification'),
]

hack/login/models.py
from django.db import models, IntegrityError
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone
from django.core.mail import send_mail




class EmployeeAccountManager(BaseUserManager):
    def create_employee(self , matricule , password, **extra_fields ):
        if not matricule or len(matricule) <= 0 : 
            raise  ValueError("matricule field is required !")
        if not password :
            raise ValueError("Password is must !")
        employee = self.model(matricule=matricule,username=matricule, **extra_fields)
        employee.set_password(password)
        
        try:
                employee.save(using=self._db)
        except IntegrityError:
            raise IntegrityError('An employee already uses this matricule')
        return employee
    def create_superuser(self, matricule, password=None, **extra_fields):
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_employee(matricule, password, **extra_fields)
    
class EmployeeAccount(AbstractUser):
    matricule = models.CharField(max_length=20 , unique = True)   
    points = models.BigIntegerField(default=0)
    
    firstname = models.CharField(max_length=255, null=True)
    lastname = models.CharField(max_length=255, null=True)
    email = models.EmailField(max_length = 200 )
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(null=True)
    is_active = models.BooleanField(default = True)
    is_admin = models.BooleanField(default = False)
    is_staff = models.BooleanField(default = False)
    is_superuser = models.BooleanField(default = False)
    
    USERNAME_FIELD = "matricule"
      
    # defining the manager for the UserAccount model
    objects = EmployeeAccountManager()
      
    def __str__(self):
        return str(self.matricule)
      
    def has_perm(self , perm, obj = None):
        return self.is_admin
      
    def has_module_perms(self , app_label):
        return True
          

hack/login/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages


def index(request):
    return render(request, 'index.html') 


def login_view(request):
    if request.method == 'POST':
        matricule = request.POST['matricule']
        password = request.POST['password']
        user = authenticate(request, username=matricule, password=password)
        print(matricule, password)

        if user is not None:
            login(request, user)
            return redirect('login:index')  # Replace 'home' with your desired redirect URL after login
        else:
            messages.error(request, 'Invalid matricule or password.')

    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('login:login')  # Replace 'login' with your desired redirect URL after logout

hack/login/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ImpactLink</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center header-transparent">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'login:index' %}"><span>ImpactLink</span></a></h1>
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'login:index' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'profiles:certification_list' %}">Add Certifications</a></li>
          <li><a class="nav-link scrollto" href="{% url 'evenements:liste_evenements' %}">Event</a></li>
          <li><a class="nav-link scrollto" href="{% url 'login:login' %}">Login</a></li>

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero">
    
    <div class="container">
        <div class="row justify-content-between">
          <div class="col-lg-7 pt-5 pt-lg-0 order-2 order-lg-1 d-flex align-items-center">
            <div data-aos="zoom-out">
              <h1>Uniting Careers for a Positive Society <span>ImpactLink </span></h1>
              <h2>Together, let's make every career an impactful journey</h2>
              <div class="text-center text-lg-start">
                <a href="#about" class="btn-get-started scrollto">Get Started</a>
              </div>
            </div>
          </div>
          <div class="col-lg-4 order-1 order-lg-2 hero-img" data-aos="zoom-out" data-aos-delay="300">
            <div class="img-container">
              <img  src="assets/img/photo1.png" class="img-fluid animated circular-image" alt="">
            </div>
          </div>
          
        </div>
      </div>
  
      <svg class="hero-waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 28 " preserveAspectRatio="none">
        <defs>
          <path id="wave-path" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z">
        </defs>
        <g class="wave1">
          <use xlink:href="#wave-path" x="50" y="3" fill="rgba(255,255,255, .1)">
        </g>
        <g class="wave2">
          <use xlink:href="#wave-path" x="50" y="0" fill="rgba(255,255,255, .2)">
        </g>
        <g class="wave3">
          <use xlink:href="#wave-path" x="50" y="9" fill="#fff">
        </g>
      </svg>
  
    </section>
  </section><!-- End Hero -->

  <main id="main">
      <!-- ======= About Section ======= -->
      <section id="about" class="about">
        <div class="container-fluid">
  
          <div class="row">
            
  
            <div class="col-xl-7 col-lg-6 icon-boxes d-flex flex-column align-items-stretch justify-content-center py-5 px-lg-5" data-aos="fade-left">
              <h3 style="color: #3498db;">Thank you for your dedication and hard work</h3>
              <p>The way you handle tasks with grace and efficiency is commendable. Thank you for making our workplace better every day</p>
  
              <div class="icon-box" data-aos="zoom-in" data-aos-delay="100">
                <div class="icon"><i class="bx bx-fingerprint"></i></div>
                <h4 class="title"><a href="">Wellness and Relaxation</a></h4>
                <p class="description">Your health and well-being matter. Explore wellness programs, relaxation zones, and mindfulness activities that ensure a healthy work-life balance</p>
              </div>
  
              <div class="icon-box" data-aos="zoom-in" data-aos-delay="200">
                <div class="icon"><i class="bx bx-gift"></i></div>
                <h4 class="title"><a href="">Employee Assistance Programs</a></h4>
                <p class="description">our well-being is our priority. Explore employee assistance programs offering counseling services, health resources, and support networks for you and your family.</p>
              </div>
  
              <div class="icon-box" data-aos="zoom-in" data-aos-delay="300">
                <div class="icon"><i class="bx bx-atom"></i></div>
                <h4 class="title"><a href="">Empowering Workspaces</a></h4>
                <p class="description">Step into workspaces designed to empower you. Enjoy ergonomic seating, spacious workstations, and vibrant surroundings that inspire creativity and productivity</p>
              </div>
  
            </div>
          </div>
  
        </div>
      </section>
  </main>

  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

hack/login/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(to right, #3498db 50%, #f8f9fa 50%);
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }

        .login-container {
            display: flex;
            align-items: center;
            justify-content: space-around;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            width: 600px;
            overflow: hidden;
        }

        .login-container img {
            width: 150px;
            height: auto;
            opacity: 0;
            animation: fadeInDown 1s forwards;
        }

        .login-form {
            width: 60%;
            background-color: #ffffff;
            padding: 20px;
            border-radius: 10px;
        }

        @keyframes fadeInDown {
            from {
                opacity: 0;
                transform: translateY(-20px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
    </style>
</head>

<body>
    <div class="login-container">
        <img src="{% static 'img/welcome.png' %}" alt="User Image">
        <form class="login-form" method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <h2>Login</h2>
            <div class="form-group">
                <label for="matricule">Matricule:</label>
                <input type="text" class="form-control" id="matricule" name="matricule" placeholder="Enter your matricule">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Enter your password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>

    <!-- Include Bootstrap JS and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>

</html>