hack/evenement/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "evenements"
urlpatterns = [
    path('', views.liste_evenements, name='liste_evenements'),
    path('evenement/<int:pk>/join/', views.join_event, name='join_event'),
]

hack/hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('login.urls')),
    path('profile/', include('profileUser.urls')),
    path('evenement/', include('evenement.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hack/login/urls.py
from django.urls import path
from . import views


app_name= "login"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

hack/profileUser/urls.py
from django.urls import path
from . import views

app_name= "profiles"
urlpatterns = [
    # Other URL patterns...
    path('', views.profile_view, name='profile'),
    path('certifications/', views.certification_list, name='certification_list'),
    path('create/', views.add_certification, name='add_certifications'),
    path('update/<str:pk>', views.update_certification, name='update_certification'),
    path('delete/<str:pk>', views.delete_certification, name='delete_certification'),
]

hack/profileUser/models.py
from django.db import models
from login.models import EmployeeAccount
class Experience(models.Model):
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    startDate = models.DateField(default=None, null=True, blank=True)
    endDate = models.DateField(default=None, null=True, blank=True)
    description = models.TextField()
    current = models.BooleanField(default=False)

    
class Education(models.Model):
    establishment = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    degree = models.CharField(max_length=255)
    field = models.CharField(max_length=255)
    date = models.DateField(default=None, null=True, blank=True)
    current = models.BooleanField(default=False)

    
class Skill(models.Model):
    skill = models.CharField(max_length=255)

    
class Language(models.Model):
    language = models.CharField(max_length=255)
    level = models.CharField(max_length=255)


class Interests(models.Model):
    interest = models.CharField(max_length=255)
    
class Certification(models.Model):
    certificate = models.CharField(max_length=255)
    platforme = models.CharField(max_length=255)
    dateD = models.DateField(default=None, blank=True)
    pdf_file = models.FileField(upload_to='pdfs/')


class Community(models.Model):
    name = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    status = models.CharField(max_length=255)
    startDate = models.DateField(default=None, null=True, blank=True)
    endDate = models.DateField(default=None, null=True, blank=True)
    description = models.TextField()

    
class Profile(models.Model):
    employee_account = models.OneToOneField(
        EmployeeAccount,
        on_delete=models.CASCADE,
        related_name='profile'
    )
    avatar = models.ImageField(default="avatar.svg", null = True )
    profileTitle = models.CharField(max_length=255)
    profileDescription = models.TextField()
    phone = models.CharField(null = True, max_length=100) 
    country = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    postalCode = models.CharField(max_length=4)
    birthDate = models.DateField(default=None, null=True, blank=True)
    gender = models.CharField(max_length=6, choices= [('M','male'), ('F', 'female')], null = True )
    linkedin = models.URLField(max_length=200, null = True) 
    certifications = models.ManyToManyField(Certification, blank=True)
    communities = models.ManyToManyField(Community, blank=True)
    interests = models.ManyToManyField(Interests, blank=True)
    languages = models.ManyToManyField(Language, blank=True)
    skills = models.ManyToManyField(Skill, blank=True)
    educations = models.ManyToManyField(Education, blank=True)
    experiences = models.ManyToManyField(Experience, blank=True)
        

hack/profileUser/views.py
from django.shortcuts import render, get_object_or_404, redirect
from login.models import EmployeeAccount
from django.contrib.auth.decorators import login_required
from .models import Certification
from django.http import HttpResponseBadRequest
from .models import Profile


@login_required
def profile_view(request):
    profile = get_object_or_404(EmployeeAccount, matricule=request.user.matricule)
    return render(request, 'profile.html', {'profile': profile})



@login_required
def certification_list(request):
    profile = request.user.profile 
    certifications = profile.certifications.all() 
    return render(request, 'certification_list.html', {'certifications': certifications})



@login_required
def add_certification(request):

    if request.method == 'POST':
        certificate = request.POST.get('certificate')
        platforme = request.POST.get('platforme')
        dateD = request.POST.get('d')
        pdf_file = request.FILES.get('pdf_file')


        #if not (certificate and platforme and dateD and pdf_file):
        #    return HttpResponseBadRequest("Invalid form data"+ dateD)

        employee_account = get_object_or_404(EmployeeAccount, matricule=request.user.matricule)
        profile = get_object_or_404(Profile, employee_account=employee_account)

        #profile = Profile.objects.get(employee_account__user)
        
        certification = Certification(certificate=certificate, platforme=platforme, dateD = dateD, pdf_file = pdf_file)
        certification.save()
        
        profile.certifications.add(certification)
                
        return redirect("profiles:certification_list")

    return render(request, "add_certification.html")
    


@login_required
def update_certification(request, pk):
    certification = get_object_or_404(Certification, pk=pk)
    if request.method == 'POST':
        certification.certificat = request.POST.get('certificat')
        certification.prenom = request.POST.get('platform')
        certification.date = request.POST.get('date')

        certification.save()
        return redirect('liste_certifications')
    return render(request, 'update_certification.html')


@login_required
def delete_certification(request, pk):
    certification = get_object_or_404(Certification, pk=pk)
    certification.delete()
    return redirect('liste_certifications')

hack/profileUser/templates/add_certification.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certifications</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
     <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(to right, #3498db, #87CEEB);
            padding: 30px;
            margin: 0;
            height: 70vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        #admissionForm {
            display: none;
        }

        form {
            max-width: 400px;
            background-color: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            opacity: 0;
            animation: fadeIn 1s forwards, fadeIn 1s forwards;
            animation-delay: 0.5s;
            margin-left: 32%;
            position: relative;
        }

        h2 {
            margin-bottom: 5%;
            font-weight: bold;
            color: #fff;
            padding: 10px;
            border-radius: 10px;
            margin-bottom: 20px;
            opacity: 0;
            animation: fadeIn 1s forwards, moveUp 1s forwards;
        }

        .admission {
            text-align: center;
            opacity: 0;
            animation: fadeIn 1s forwards, moveUp 1s forwards;
        }

        .toggle-icon {
            position: absolute;
            bottom: 10px;
            right: 10px;
            background-color: #3498db;
            color: #fff;
            padding: 10px;
            border-radius: 50%;
            cursor: pointer;
        }

        .add-button {
            background-color: #3498db;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px;
        }

        .add-button:hover {
            background-color: #2c82c7;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }

        @keyframes moveUp {
            from {
                transform: translateY(20px);
            }

            to {
                transform: translateY(0);
            }
        }
    </style>
</head>

<body>
   <!-- ======= Header ======= -->
   <header id="header" class="fixed-top d-flex align-items-center header-transparent">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'login:index' %}"><span>ImpactLink</span></a></h1>
        
      </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'login:index' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'profiles:certification_list' %}">Add Certifications</a></li>
          <li><a class="nav-link scrollto" href="{% url 'evenements:liste_evenements' %}">Event</a></li>
          <li><a class="nav-link scrollto" href="{% url 'login:login' %}">Login</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="admission">Certificate Form</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" id="certificate form">
                <form method="post" action="{% url 'profiles:add_certifications' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="certificate">Certificate Name</label>
                        <input type="text" class="form-control" name="certificate" placeholder="Enter the certificate name">
                    </div>
                    <div class="form-group">
                        <label for="platforme">Plateform</label>
                        <input type="text" class="form-control" name="platforme" placeholder="Enter your platform name">
                    </div>
                    <div class="form-group">
                        <label for="d">Date</label>
                        <input type="date" class="form-control" name="d" placeholder="Select the platform date">
                    </div>
                    
                    <div class="form-group">
                        <label for="pdf_file">Upload Certificate</label>
                        <input type="file" class="form-control-file" name="pdf_file">
                    </div>
                    <button type="submit" class="btn btn-primary" style="background-color:#2c82c7;">Submit</button>
                </form>
            </div>
            <div id="initialMessage" class="admission" style="align-self:center;padding-left: 32%;">
        
    </div>


</body>

</html>

hack/profileUser/templates/certification_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certifications</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
     <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <style>
        body {
            background: linear-gradient(to right, #3498db, #87CEEB);
            padding: 30px;
            margin: 0;
            height: 70vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        #admissionForm {
            display: none;
        }

        form {
            max-width: 400px;
            background-color: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            opacity: 0;
            animation: fadeIn 1s forwards, fadeIn 1s forwards;
            animation-delay: 0.5s;
            margin-left: 32%;
            position: relative;
        }

        h2 {
            margin-bottom: 5%;
            font-weight: bold;
            color: #fff;
            padding: 10px;
            border-radius: 10px;
            margin-bottom: 20px;
            opacity: 0;
            animation: fadeIn 1s forwards, moveUp 1s forwards;
        }

        .admission {
            text-align: center;
            opacity: 0;
            animation: fadeIn 1s forwards, moveUp 1s forwards;
        }

        .toggle-icon {
            position: absolute;
            bottom: 10px;
            right: 10px;
            background-color: #3498db;
            color: #fff;
            padding: 10px;
            border-radius: 50%;
            cursor: pointer;
        }

        .add-button {
            background-color: #3498db;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px;
        }

        .add-button:hover {
            background-color: #2c82c7;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }

        @keyframes moveUp {
            from {
                transform: translateY(20px);
            }

            to {
                transform: translateY(0);
            }
        }
    </style>
</head>

<body>
   <!-- ======= Header ======= -->
   <header id="header" class="fixed-top d-flex align-items-center header-transparent">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <h1><a href="{% url 'login:index' %}"><span>ImpactLink</span></a></h1>
        
      </div>

      <nav id="navbar" class="navbar">
        <ul>
            <li><a class="nav-link scrollto active" href="{% url 'login:index' %}">Home</a></li>
            <li><a class="nav-link scrollto" href="{% url 'profiles:certification_list' %}">Add Certifications</a></li>
            <li><a class="nav-link scrollto" href="{% url 'evenements:liste_evenements' %}">Event</a></li>
            <li><a class="nav-link scrollto" href="{% url 'login:login' %}">Login</a></li>

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
                {% if certifications is empty %}
                <img src="{% static 'img/icons8-empty-48.png' %}" style="padding-bottom: 3%;">
                <p style="background-color: #fff;opacity: 70%; padding: 4%;">No certification added yet. Click the button below to add.</p>
                {% else %}
                <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">Certificat</th>
                        <th scope="col">Platform</th>
                        <th scope="col">Date</th>
                        <th scope="col">Certificat PDF</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for certification in certifications%}
                            <tr>
                                <th scope="row">{{ certification.certificate }}</th>
                                <td>{{ certification.platforme }}</td>
                                <td>{{ certification.dateD }}</td>
                                <td>
                                    {% if certification.pdf_file%}
                                        <a href="{{ certification.pdf_file.url }}" download="{{ certification.certificate }}.pdf" class="btn btn-primary" style="margin-top: 10px;">
                                        Download PDF
                                    </a>
                                    {%else%}
                                        <p style="color:#ff0000">No file found</p>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}   
                    </tbody>
                  </table>
                {% endif %} 

            
            </div>
        </div>
    </div>
  

    <input type="button" id="addbtn" class="add-button" style="border-radius: 20%;" value="Add" onclick="redirectToAddCertifications()">

    <script>
        
        function redirectToAddCertifications() {
            // Redirect to the specified URL
            window.location.href = "{% url 'profiles:add_certifications' %}";
        }
        function toggleForm() {
            const admissionForm = document.getElementById('admissionForm');
            const initialMessage = document.getElementById('initialMessage');
            var addbtn = document.getElementById('addbtn');

            if (admissionForm.style.display === 'none') {
                admissionForm.style.display = 'block';
                initialMessage.style.display = 'none';
                addbtn.value="cancel";

            } else {
                admissionForm.style.display = 'none';
                initialMessage.style.display = 'block';
            }
        }
    </script>
</body>

</html>

hack/profileUser/templates/profile.html
<!-- profiles/templates/profiles/profile_detail.html -->


{% block content %}
  <h1>{{ profile.profileTitle }}</h1>
  <p>{{ profile.profileDescription }}</p>
  <p>Phone: {{ profile.phone }}</p>
  <p>Country: {{ profile.country }}</p>
  <!-- Add more fields as needed -->

  <!-- Example of displaying avatar image -->
  {% if profile.avatar %}
    <img src="{{ profile.avatar.url }}" alt="{{ profile.profileTitle }} Avatar">
  {% endif %}

  <!-- Displaying skills, certifications, etc. -->
  <h2>Skills</h2>
  <ul>
    {% for skill in profile.skills.all %}
      <li>{{ skill.name }}</li>
    {% endfor %}
  </ul>

  <!-- Add similar blocks for other related fields -->
{% endblock %}