hack/evenement/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "evenements"
urlpatterns = [
    path('', views.liste_evenements, name='liste_evenements'),
    path('evenement/<int:pk>/join/', views.join_event, name='join_event'),
]

hack/hack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('login.urls')),
    path('profile/', include('profileUser.urls')),
    path('evenement/', include('evenement.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hack/login/urls.py
from django.urls import path
from . import views


app_name= "login"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout')
]

hack/profileUser/urls.py
from django.urls import path
from . import views

app_name= "profiles"
urlpatterns = [
    # Other URL patterns...
    path('', views.profile_view, name='profile'),
    path('certifications/', views.certification_list, name='certification_list'),
    path('create/', views.add_certification, name='add_certifications'),
    path('update/<str:pk>', views.update_certification, name='update_certification'),
    path('delete/<str:pk>', views.delete_certification, name='delete_certification'),
]

hack/evenement/models.py
from django.db import models
from login.models import EmployeeAccount

class Evenement(models.Model):
    id = models.AutoField(primary_key=True)
    image = models.ImageField(upload_to='images_evenements/')
    nom = models.CharField(max_length=100)
    organisation = models.CharField(max_length=100)
    lieu = models.CharField(max_length=100)
    date = models.DateField()
    description = models.CharField(max_length=1000)
    participants = models.ManyToManyField(EmployeeAccount, blank=True)

    class Meta:
        verbose_name = ("Evenement")
        verbose_name_plural = ("Evenements")

    def __str__(self):
        return self.nom

hack/login/models.py
from django.db import models, IntegrityError
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone
from django.core.mail import send_mail




class EmployeeAccountManager(BaseUserManager):
    def create_employee(self , matricule , password, **extra_fields ):
        if not matricule or len(matricule) <= 0 : 
            raise  ValueError("matricule field is required !")
        if not password :
            raise ValueError("Password is must !")
        employee = self.model(matricule=matricule,username=matricule, **extra_fields)
        employee.set_password(password)
        
        try:
                employee.save(using=self._db)
        except IntegrityError:
            raise IntegrityError('An employee already uses this matricule')
        return employee
    def create_superuser(self, matricule, password=None, **extra_fields):
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_employee(matricule, password, **extra_fields)
    
class EmployeeAccount(AbstractUser):
    matricule = models.CharField(max_length=20 , unique = True)   
    points = models.BigIntegerField(default=0)
    
    firstname = models.CharField(max_length=255, null=True)
    lastname = models.CharField(max_length=255, null=True)
    email = models.EmailField(max_length = 200 )
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(null=True)
    is_active = models.BooleanField(default = True)
    is_admin = models.BooleanField(default = False)
    is_staff = models.BooleanField(default = False)
    is_superuser = models.BooleanField(default = False)
    
    USERNAME_FIELD = "matricule"
      
    # defining the manager for the UserAccount model
    objects = EmployeeAccountManager()
      
    def __str__(self):
        return str(self.matricule)
      
    def has_perm(self , perm, obj = None):
        return self.is_admin
      
    def has_module_perms(self , app_label):
        return True
          

hack/evenement/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Evenement
from login.models import EmployeeAccount
from django.contrib.auth.decorators import login_required


def liste_evenements(request):
    evenements = Evenement.objects.all()
    return render(request, "liste_evenements.html", {"evenements": evenements})

@login_required
def join_event(request, pk):
    employee = request.user  # The logged-in user
    evenement = get_object_or_404(Evenement, pk=pk)
    
    evenement.participants.add(employee)
    return redirect('evenements:liste_evenements')

hack/login/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages


def index(request):
    return render(request, 'index.html') 


def login_view(request):
    if request.method == 'POST':
        matricule = request.POST['matricule']
        password = request.POST['password']
        user = authenticate(request, username=matricule, password=password)
        print(matricule, password)

        if user is not None:
            login(request, user)
            return redirect('login:index')  # Replace 'home' with your desired redirect URL after login
        else:
            messages.error(request, 'Invalid matricule or password.')

    return render(request, 'login.html')

def logout_view(request):
    logout(request)
    return redirect('login:login')  # Replace 'login' with your desired redirect URL after logout

hack/evenement/templates/liste_evenements.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>ImpactLink</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/aos/aos.css'}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css'}" rel="stylesheet">
  <link href="{% static 'vendor/boxicons/css/boxicons.min.css'}" rel="stylesheet">
  <link href="{% static 'vendor/glightbox/css/glightbox.min.css'}" rel="stylesheet">
  <link href="{% static 'vendor/remixicon/remixicon.css'}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css'}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #3498db;
        }

        .event-card-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .event-card {
            margin: 20px;
            max-width: 300px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            transition: box-shadow 0.3s ease-in-out;
        }

        .event-card:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        }

        .event-card img {
            width: 100%;
            height: 150px;
            object-fit: cover;
        }

        .event-details {
            padding: 20px;
        }

        .event-title {
            font-size: 1.5em;
            font-weight: bold;
            margin-bottom: 10px;
            color: #3498db;
        }

        .event-info {
            margin-bottom: 10px;
        }

        .event-info span {
            font-weight: bold;
            color: #3498db;
        }

        .event-description {
            font-size: 0.9em;
            margin-bottom: 10px;
        }

        .event-participants-container {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .participants-circle {
          
            background-color: #3498db;
            border-radius: 50%;
            display: flex;
            justify-content: center;
            align-items: center;
            margin-right: 10px;
        }

        .participants-circle img {
            width: 20px; /* Adjust the image size as needed */
            height: 20px; /* Adjust the image size as needed */
            border-radius: 50%;
        }

        .event-score {
            font-size: 0.8em;
            color: #555;
        }
        body {
            background: linear-gradient(to right, #3498db, #87CEEB);
            padding: 30px;
            margin: 0;
            height: 70vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }



        form {
            max-width: 400px;
            background-color: #fff;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            opacity: 0;
            animation: fadeIn 1s forwards, fadeIn 1s forwards;
            animation-delay: 0.5s;
            margin-left: 32%;
            position: relative;
        }

        h2 {
            margin-bottom: 5%;
            font-weight: bold;
            color: #fff;
            padding: 10px;
            border-radius: 10px;
            margin-bottom: 20px;
            opacity: 0;
            animation: fadeIn 1s forwards, moveUp 1s forwards;
        }


   
        @keyframes fadeIn {
            from {
                opacity: 0;
            }

            to {
                opacity: 1;
            }
        }

        @keyframes moveUp {
            from {
                transform: translateY(20px);
            }

            to {
                transform: translateY(0);
            }
        }
    </style>
    
</head>

<body>
    <header id="header" class="fixed-top d-flex align-items-center header-transparent">
        <div class="container d-flex align-items-center justify-content-between">
    
          <div class="logo">
            <h1><a href="{% url 'login:index' %}"><span>ImpactLink</span></a></h1>
          </div>
    
          <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto active" href="{% url 'login:index' %}">Home</a></li>
                <li><a class="nav-link scrollto" href="{% url 'profiles:certification_list' %}">Add Certifications</a></li>
                <li><a class="nav-link scrollto" href="{% url 'evenements:liste_evenements' %}">Event</a></li>
                <li><a class="nav-link scrollto" href="{% url 'login:login' %}">Login</a></li>
    
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
          </nav><!-- .navbar -->
    
        </div>
    </header><!-- End Header -->

    <div class="event-card-container" style="padding:2%;">
        
        
    
            {% for evenement in evenements %}   
                <div class="event-card">
                    <img src="{{ evenement.image.url }}" alt="event Image">
                    <div class="event-details">
                    <div class="event-title">{{ evenement.nom }}</div>
                    <div class="event-info">
                        <span>Name:</span> {{ evenement.organisation }}
                    </div>
                    <div class="event-info">
                        <span>Location:</span> {{ evenement.lieu }}
                    </div>
                    <div class="event-info">
                        <span>Date:</span> {{ evenement.date }}
                    </div>
                    <div class="event-description">
                        {{ evenement.description }}
                    </div>
                    <div class="event-participants-container">
                        Participants:
                        <div class="participants-circle">
                            {% for participant in evenement.participants.all %}
                                {% if participant.profile.avatar %}
                                    <img src="{{ participant.image.url }}" alt="Participant Image">
                                {% else %}
                                    <img src="images/photo-participant.profile.avatar" alt="Default Participant Image">
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                    <button class="btn btn-primary" style="background-color:#3498db;">
                        <a href="{% url 'evenements:join_event' evenement.pk %}" style="text-decoration: none; color: white;">Join Event</a>
                    </button>

                </div>
            
            {% endfor %}
    </div>
</body>

</html>

hack/evenement/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>

    <form method="POST" action ="{% url 'employee:login' %}" onsubmit="error_message()">
        {% csrf_token %}
        <input type="text" id="matricule" placeholder="Enter matricule" required/>
        <input type="password" id="password" placeholder="Enter password" required/>
        <button type="submit">Login</button>
    </form>
</body>
</html>